Repository halo-dev/plugin-search-widget, pull requests merged in 2024-08, with the labels that each got.

#43 feat: add support for passing options to the search component
  package.json
  packages/search-widget/package.json
  packages/search-widget/src/search-form.ts
  packages/search-widget/src/search-modal.ts
  packages/widget/src/index.ts
  pnpm-lock.yaml
  src/main/resources/static/search-widget.iife.js
Labels: kind/feature, approved, lgtm, release-note

#44 Upgrade Gradle to 8.9
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
Labels: approved, lgtm, release-note

#42 refactor: ui design
  README.md
  build.gradle
  images/preview.png
  package.json
  packages/example/.gitignore
  packages/example/index.html
  packages/example/package.json
  packages/example/src/main.ts
  packages/example/tsconfig.json
  packages/example/vite.config.ts
  packages/search-widget/.eslintrc.json
  packages/search-widget/index.html
  packages/search-widget/package.json
  packages/search-widget/src/constants/index.ts
  packages/search-widget/src/search-form.ts
  packages/search-widget/src/search-modal.ts
  packages/search-widget/src/styles/base.ts
  packages/search-widget/src/styles/var.ts
  packages/search-widget/uno.config.ts
  packages/search-widget/var.css
  packages/search-widget/vite.config.dev.ts
  packages/search-widget/vite.config.lib.ts
  pnpm-lock.yaml
  src/main/resources/static/search-widget.iife.js
  src/main/resources/static/style.css
Labels: approved, lgtm, release-note

#45 fix: resolve issue preventing page navigation after selecting search result
  packages/search-widget/src/search-form.ts
Labels: kind/bug, do-not-merge/release-note-label-needed, approved, lgtm

#46 refactor: improve line height style for search results
  packages/search-widget/src/search-form.ts
Labels: approved, lgtm, release-note, kind/improvement
